# Generated by Django 4.2.4 on 2023-12-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tus_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('House_Description', models.CharField(max_length=500)),
                ('Street', models.CharField(max_length=100)),
                ('House_number', models.SmallIntegerField(max_length=10)),
                ('Content', models.TextField(max_length=5000)),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
    ]
