# Generated by Django 4.2.4 on 2023-12-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_tus_pedidos_house_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tus_pedidos',
            options={'ordering': ['id'], 'verbose_name': 'Tu Pedido', 'verbose_name_plural': 'Tus Pedidos'},
        ),
        migrations.AddField(
            model_name='tus_pedidos',
            name='image',
            field=models.ImageField(default='null', upload_to='', verbose_name='imagen del Poducto'),
        ),
        migrations.AlterField(
            model_name='tus_pedidos',
            name='Content',
            field=models.TextField(max_length=400, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='tus_pedidos',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='tus_pedidos',
            name='House_Description',
            field=models.CharField(max_length=500, verbose_name='Describe tu Casa'),
        ),
        migrations.AlterField(
            model_name='tus_pedidos',
            name='House_number',
            field=models.SmallIntegerField(verbose_name='Numero de Casa'),
        ),
        migrations.AlterField(
            model_name='tus_pedidos',
            name='Street',
            field=models.CharField(max_length=100, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='tus_pedidos',
            name='Title',
            field=models.CharField(max_length=250, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='tus_pedidos',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='tus_pedidos',
            name='public',
            field=models.BooleanField(verbose_name='Publico'),
        ),
    ]
